### ISSUE TITLE
RocksDB support

### ISSUE THREAD

**Issue by vasilenkoalexey** [storj-archived/kfs#58]
Propose to implement the support of modern KVS [RocksDB](https://github.com/facebook/rocksdb)
There is nodejs binding [A Low-level Node.js RocksDB](https://www.npmjs.com/package/rocksdb), which implement same API as LevelDown, used in KFS. So the implementation of support should be easy.
RocksDB is optimized for Flash or RAM, but the official documentation also says

> RocksDB features highly flexible configuration settings that may be tuned to run on a variety of production environments, including pure memory, Flash, hard disks or HDFS. It supports various compression algorithms and good tools for production support and debugging.

> It has multi-threaded compactions, making it specially suitable for storing multiple terabytes of data in a single database.

So it looks most relevant as a backend for a large shard(several terabytes). Also RocksDB is more tunable and have some features which not present at LevelDB.

Both RocksDB and LevelDB have similar benchmark tool db_bench. Thus, it is possible to perform comparative performance tests and estimate the increase in read/write speed.

Now using RocksDB instead of LevelDB can be an experimental function that is activated when a node is created. And in the future it can be a good substitute for an outdated LevelDB.

**Comment by vasilenkoalexey** [comment]
I did some tests and RocksDB lose. Useless for usual HDD. Can be closed.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
